version: '3.7'
services:
  db:
    container_name: dukedata-postgres
    build: .
    restart: unless-stopped
    ports:
      - '5435:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  arena-db:
    image: us.gcr.io/arenaxlab/postgres:dev-latest
    platform: linux/amd64
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5434:5432"
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local